; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dev]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
    lvgl/lvgl@^8.4.0
monitor_speed = 115200
upload_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_SUPPRESS_DEFINE_CHECK
    -I./src
    -I./src/ui/generated/src
    -I./components
    -I./components/*/include
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter = 
    +<*> 
    +<ui/generated/src/ui/*.c>
    +<ui/generated/src/ui/*.cpp>
    -<ui_backup/> 
    -<display/esp32_s3.c>
    -<display/esp32_s3.h>
    -<main.c>

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
monitor_filters = esp32_exception_decoder, colorize
monitor_rts = 0
monitor_dtr = 0
