; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dev]
platform = espressif32@6.10.0
board = crowpanel advance_s3
framework = arduino
lib_deps = 
    lvgl/lvgl@^8.4.0
    adafruit/Adafruit BusIO@^1.14.5
    adafruit/Adafruit GFX Library@^1.11.9
    Wire
monitor_speed = 115200
upload_speed = 115200
build_unflags = 
    -std=gnu++11
build_flags = 
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_SUPPRESS_DEFINE_CHECK
    -I./src

; Include Arduino display driver files and exclude ESP-IDF files
build_src_filter = 
    +<*> 
    -<display/esp32_s3.c> 
    -<display/esp32_s3.h>
    -<gui/gui.c> 
    -<main.c> 
    -<ui_backup/> 
    -<ui/screens.c> 
    -<ui/ui.c> 
    -<ui/ui_init.c> 
    -<ui/vars.c> 
    -<ui/actions.c> 
    -<ui/generated/>
    +<display/esp32_s3_arduino.cpp>
    +<display/esp32_s3_arduino.h>
    +<display/pins.h>
    +<display/display_config.h>
