#include "ui_init.h"
#include "ui.h"
#include "lvgl.h"

void ui_app_init(void) {
    // Initialize the UI generated by EEZ Studio
    ui_init();  // This will create screens and load the main screen
}

void ui_app_update(void) {
    // Update UI elements periodically
    lv_timer_handler();
    ui_tick();  // This will update the current screen
} 