#include "ui_init.h"
#include "ui.h"
#include "lvgl.h"

void ui_app_init(void) {
    // Initialize the UI generated by EEZ Studio
    ui_init();  // This will create screens and load the main screen
}

#include "esp_log.h"
#include "vars.h"
#include "screens.h"

extern objects_t objects;

void ui_app_update(void) {
    lv_timer_handler(); // This handles LVGL timer events
    ui_tick(); // Call the main UI tick function
}