#include "ui_init.h"
#include "ui.h"
#include "lvgl.h"

void ui_init(void) {
    // Initialize the UI generated by EEZ Studio
    ui_init_start();
}

void ui_update(void) {
    // Update UI elements periodically
    lv_timer_handler();
} 